### ISSUE TITLE
Poimenovanje datotek

### ISSUE THREAD

**Issue by jernejbanevec** [lanazajc/APPR-2018-19#1]
Zdravo,
svetujem, da se izogibaš šumnikom in presledkom, pa tudi drugim posebnim znakom, kot npr. oklepaji ali $ (ali katerikoli R-jev operator), tako v imenih datotek (iz imen datotek tako svetujem da odstraniš presledke) kot pozneje, ko boš podatke uvozila, tudi v imenih stolpcev, saj se s tem izogneš morebitnim težavam zaradi razlik v sistemih. Tako boš potem svoj uvoz podatkov hitreje (in z manj težavami) pravilno napisala.

**Comment by lanazajc** [comment]
Hvala za nasvet, sem popravila.
