### ISSUE TITLE
Težave z read_csv2

### ISSUE THREAD

**Issue by lanazajc** [lanazajc/APPR-2018-19#3]
Pozdravljeni, 
na faksu sem uvozila tabelo s funkcijo read_csv2, in jo spravila v tidy data. Na vajah je vse delovalo normalno, doma pa mi, ko zaženem to funkcijo, napiše:
Error in read_csv2("podatki/dejavnost_izob.csv", col_names = stolpci,  : 
  could not find function "read_csv2"
Prosim za nasvet oz. pomoč kako to odpraviti. 
Hvala :)

**Comment by jaanos** [comment]
Očitno knjižnica `readr` ni bila uvožena. Svetujem, da pred začetkom dela poženeš `libraries.r`, da se ti naložijo vse potrebne knjižnice. Tam lahko potem tudi naložiš morebitne druge knjižnice, ki jih potrebuješ.

Bodi pozorna, če se morda nalaganje ustavi z napako - to bi pomenilo, da knjižnice še nimaš nameščene. V tem primeru bo potrebno manjkajoče knjižnice namestiti - v RStudiu v meniju *Tools* izberi *Install Packages...*, nato pa pod *Packages* vpiši imena manjkajočih knjižnic (npr. `readr`). Najbolje bo, da poskrbiš, da so nameščene vse knjižnice, ki so omenjene v `README.md` (seznam že namesčenih knjižnic lahko vidiš desno spodaj v zavihku **Packages**).

**Comment by lanazajc** [comment]
Hvala za pomoč, se uvozila vse knjižnice in namestila vse knjižnice, sedaj pa se, ko zaženem read_csv2 pojavi še več težav. 
" > place_dejavnost_izobrazba <- read_csv2("podatki/dejavnost_izob.csv", 
+                                        col_names = stolpci, 
+                                        skip=4, na=c("", "-", " "),
+                                        locale=locale(encoding="Windows-1250"))
Using ',' as decimal and '.' as grouping mark. Use read_delim() for more control.
Parsed with column specification:
cols(
  Dejavnost = col_character(),
  Izobrazba = col_character(),
  Spol = col_character(),
  `2010` = col_double(),
  `2011` = col_double(),
  `2012` = col_double(),
  `2013` = col_double(),
  `2014` = col_double(),
  `2015` = col_double()
)
Warning: 90 parsing failures.
row col  expected    actual                         file
  1  -- 9 columns 1 columns 'podatki/dejavnost_izob.csv'
  2  -- 9 columns 2 columns 'podatki/dejavnost_izob.csv'
  5  -- 9 columns 2 columns 'podatki/dejavnost_izob.csv'
  8  -- 9 columns 2 columns 'podatki/dejavnost_izob.csv'
 11  -- 9 columns 1 columns 'podatki/dejavnost_izob.csv'
... ... ......... ......... ............................
See problems(...) for more details. "

Lahko prosim pogledate, kje je težava? 
Hvala

**Comment by jaanos** [comment]
Vse je v redu - opozorila so zato, ker imajo vrstice različna števila polj (to so ravno tiste vrstice, ki jih kasneje izpustiš z `drop_na`). Pomembno je, da imajo stolpci prave tipe (npr. `col_double()` za stolpce s podatki za vsako leto, saj gre za števila).

Še to: da v issueju lepo prikažeš kodo, naredi tako:

~~~
```R
koda
```
~~~

Oznaka `R` pomeni, da je koda v R-ju in se bo potem ustrezno pobarvala (po potrebi lahko seveda uporabiš tudi druge programske jezike). S klikom na *View* lahko pred objavo vidiš, kako bo ta izgledala.
